# Generated by Django 5.2.1 on 2025-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                help_text="Укажите chat-id в телеграмм",
                max_length=50,
                unique=True,
                verbose_name="chat-id в телеграмм",
            ),
        ),
    ]
