# Generated by Django 5.2.1 on 2025-05-23 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения",
                        max_length=200,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Укажите время, когда необходимо выполнить привычку",
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие привычки",
                        max_length=255,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("DAILY", "Ежедневно"),
                            ("1_DAY", "Каждые 2 дня"),
                            ("2_DAY", "Каждые 3 дня"),
                            ("3_DAY", "Каждые 4 дня"),
                            ("4_DAY", "Каждые 5 дней"),
                            ("5_DAY", "Каждые 6 дней"),
                            ("6_DAY", "Каждые 7 дней"),
                        ],
                        default="DAILY",
                        help_text="Укажите тип периодичности выполнения",
                        max_length=5,
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение полезной привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "lead_time",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Время необходимое для пыполнения привычки",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите можно ли показывать привычку в общий доступ.",
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["start_time"],
            },
        ),
    ]
