# Generated by Django 5.2.1 on 2025-05-23 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                help_text="Введите автора привычки",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор привычки",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связаную приятную привычку",
                limit_choices_to={"is_nice": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habit",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
