# Generated by Django 5.2.1 on 2025-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("1_DAY", "Ежедневно"),
                    ("2_DAY", "Каждые 2 дня"),
                    ("3_DAY", "Каждые 3 дня"),
                    ("4_DAY", "Каждые 4 дня"),
                    ("5_DAY", "Каждые 5 дней"),
                    ("6_DAY", "Каждые 6 дней"),
                    ("7_DAY", "Каждые 7 дней"),
                ],
                default="1_DAY",
                help_text="Укажите тип периодичности выполнения",
                max_length=5,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
