# Generated by Django 5.2.1 on 2025-05-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="is_published",
            new_name="is_public",
        ),
    ]
