# Generated by Django 5.2.1 on 2025-05-31 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_rename_is_published_habit_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="next_execution",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Дата следующего выполнения",
            ),
            preserve_default=False,
        ),
    ]
