# Generated by Django 5.2.1 on 2025-06-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_created_at_habit_next_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="next_execution",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата следующего выполнения"
            ),
        ),
    ]
